/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProyekRouteRouteImport } from './routes/_authenticated/proyek/route'
import { Route as AuthenticatedTimRouteImport } from './routes/_authenticated/tim'
import { Route as AuthenticatedProyekIndexRouteImport } from './routes/_authenticated/proyek.index'
import { Route as AuthenticatedProyekProjectIdRouteImport } from './routes/_authenticated/proyek.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProyekRouteRoute =
  AuthenticatedProyekRouteRouteImport.update({
    id: '/proyek',
    path: '/proyek',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimRoute = AuthenticatedTimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProyekIndexRoute =
  AuthenticatedProyekIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProyekRouteRoute,
  } as any)
const AuthenticatedProyekProjectIdRoute =
  AuthenticatedProyekProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProyekRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/proyek': typeof AuthenticatedProyekRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tim': typeof AuthenticatedTimRoute
  '/proyek/$projectId': typeof AuthenticatedProyekProjectIdRoute
  '/proyek/': typeof AuthenticatedProyekIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/tim': typeof AuthenticatedTimRoute
  '/proyek/$projectId': typeof AuthenticatedProyekProjectIdRoute
  '/proyek': typeof AuthenticatedProyekIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/proyek': typeof AuthenticatedProyekRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/tim': typeof AuthenticatedTimRoute
  '/_authenticated/proyek/$projectId': typeof AuthenticatedProyekProjectIdRoute
  '/_authenticated/proyek/': typeof AuthenticatedProyekIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/proyek'
    | '/dashboard'
    | '/tim'
    | '/proyek/$projectId'
    | '/proyek/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/tim' | '/proyek/$projectId' | '/proyek'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/proyek'
    | '/_authenticated/dashboard'
    | '/_authenticated/tim'
    | '/_authenticated/proyek/$projectId'
    | '/_authenticated/proyek/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyek': {
      id: '/_authenticated/proyek'
      path: '/proyek'
      fullPath: '/proyek'
      preLoaderRoute: typeof AuthenticatedProyekRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tim': {
      id: '/_authenticated/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof AuthenticatedTimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyek/': {
      id: '/_authenticated/proyek/'
      path: '/'
      fullPath: '/proyek/'
      preLoaderRoute: typeof AuthenticatedProyekIndexRouteImport
      parentRoute: typeof AuthenticatedProyekRouteRoute
    }
    '/_authenticated/proyek/$projectId': {
      id: '/_authenticated/proyek/$projectId'
      path: '/$projectId'
      fullPath: '/proyek/$projectId'
      preLoaderRoute: typeof AuthenticatedProyekProjectIdRouteImport
      parentRoute: typeof AuthenticatedProyekRouteRoute
    }
  }
}

interface AuthenticatedProyekRouteRouteChildren {
  AuthenticatedProyekProjectIdRoute: typeof AuthenticatedProyekProjectIdRoute
  AuthenticatedProyekIndexRoute: typeof AuthenticatedProyekIndexRoute
}

const AuthenticatedProyekRouteRouteChildren: AuthenticatedProyekRouteRouteChildren =
  {
    AuthenticatedProyekProjectIdRoute: AuthenticatedProyekProjectIdRoute,
    AuthenticatedProyekIndexRoute: AuthenticatedProyekIndexRoute,
  }

const AuthenticatedProyekRouteRouteWithChildren =
  AuthenticatedProyekRouteRoute._addFileChildren(
    AuthenticatedProyekRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProyekRouteRoute: typeof AuthenticatedProyekRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTimRoute: typeof AuthenticatedTimRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProyekRouteRoute: AuthenticatedProyekRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTimRoute: AuthenticatedTimRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
